import { promises as fs } from 'node:fs'
import path from 'node:path'

// Server-side chat endpoint: runs RAG over the course embeddings and streams
// Gemini's answer back as Server-Sent Events. The API key stays on the server.

export const runtime = 'nodejs'
export const maxDuration = 60

const EMBEDDING_MODEL = 'gemini-embedding-2-preview'
const CHAT_API_BASE = 'https://api.shopaikey.com/v1/models/gemini-3.5-flash'
const EMBED_API_BASE = `https://api.shopaikey.com/v1beta/models/${EMBEDDING_MODEL}`

const GENERATION_CONFIG = {
  temperature: 0.45,
  topK: 40,
  topP: 0.9,
  maxOutputTokens: 4096,
}
const SAFETY_SETTINGS = [{ category: 'HARM_CATEGORY_HARASSMENT', threshold: 'BLOCK_NONE' }]

type EmbeddingItem = { source: string; text: string; embedding: number[] }
type HistoryItem = { role: string; text?: string; content?: string }

function getApiKey() {
  return process.env.GOOGLE_API_KEY || process.env.NEXT_PUBLIC_GOOGLE_API_KEY || ''
}

// Load + cache embeddings from data/embeddings.json (generated by `npm run ingest`).
let embeddingsCache: EmbeddingItem[] | null = null
async function loadEmbeddings(): Promise<EmbeddingItem[]> {
  if (embeddingsCache) return embeddingsCache
  let loaded: EmbeddingItem[] = []
  try {
    const file = path.join(process.cwd(), 'data', 'embeddings.json')
    const raw = await fs.readFile(file, 'utf8')
    const data = JSON.parse(raw)
    loaded = Array.isArray(data) ? data : data.embeddings ?? []
  } catch {
    loaded = []
  }
  embeddingsCache = loaded
  return loaded
}

function cosineSimilarity(a: number[], b: number[]): number {
  if (a.length !== b.length) return 0
  let dot = 0
  let magA = 0
  let magB = 0
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i]
    magA += a[i] * a[i]
    magB += b[i] * b[i]
  }
  magA = Math.sqrt(magA)
  magB = Math.sqrt(magB)
  return magA && magB ? dot / (magA * magB) : 0
}

const EMBED_TIMEOUT_MS = 6000

async function embedQuery(text: string): Promise<number[]> {
  const apiKey = getApiKey()
  if (!apiKey) return []

  // Cap the RAG embedding round-trip: if the upstream is slow/overloaded, skip
  // context retrieval rather than making the whole answer wait on it.
  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), EMBED_TIMEOUT_MS)
  try {
    const response = await fetch(`${EMBED_API_BASE}:embedContent?key=${apiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ content: { parts: [{ text }] } }),
      signal: controller.signal,
    })
    if (!response.ok) return []
    const data = await response.json()
    return data?.embedding?.values ?? []
  } catch {
    return []
  } finally {
    clearTimeout(timeout)
  }
}

const RAG_TOP_K = 6
const RAG_MAX_CHARS_PER_CHUNK = 1200

async function buildRelevantContext(userMessage: string): Promise<string> {
  try {
    const embeddings = await loadEmbeddings()
    if (embeddings.length === 0) return ''

    const userEmbedding = await embedQuery(userMessage)
    if (userEmbedding.length === 0) return ''

    const top = embeddings
      .map((item) => ({ text: item.text, score: cosineSimilarity(userEmbedding, item.embedding) }))
      .sort((a, b) => b.score - a.score)
      .slice(0, RAG_TOP_K)

    if (top.length === 0) return ''

    const blocks = top
      .map((ctx, i) => `[Trích đoạn ${i + 1}]\n${ctx.text.slice(0, RAG_MAX_CHARS_PER_CHUNK).trim()}`)
      .join('\n\n')

    return `\n\n===== TRÍCH DẪN TỪ GIÁO TRÌNH (căn cứ ưu tiên để trả lời) =====\n${blocks}\n===== HẾT TRÍCH DẪN =====`
  } catch {
    return ''
  }
}

function buildSystemPrompt(relevantContext: string): string {
  return `Bạn là Trợ lý học tập môn Chủ nghĩa xã hội khoa học (thuộc chủ nghĩa Mác - Lênin), do Nhóm 7 xây dựng cho học phần MLN131. Tài liệu nền của bạn là giáo trình "Chủ nghĩa xã hội khoa học" bản chính thống (Bộ Giáo dục và Đào tạo).

**Bối cảnh:** Người đang trò chuyện với bạn là thầy cô, các bạn sinh viên và khách tham quan đến trải nghiệm sản phẩm — họ KHÔNG phải là thành viên Nhóm 7. Hãy xưng hô trung lập, lịch sự (ví dụ: "bạn", hoặc "thầy/cô" nếu phù hợp).

**Mục tiêu:** Giải đáp và đồng hành cùng người dùng về chủ nghĩa Mác - Lênin và chủ nghĩa xã hội khoa học, bám sát nội dung giáo trình.

**PHẠM VI (QUAN TRỌNG):**
- Bạn CHỈ trả lời các câu hỏi thuộc phạm vi giáo trình Chủ nghĩa xã hội khoa học và chủ nghĩa Mác - Lênin, ví dụ: sứ mệnh lịch sử của giai cấp công nhân; chủ nghĩa xã hội và thời kỳ quá độ lên chủ nghĩa xã hội; dân chủ xã hội chủ nghĩa và nhà nước xã hội chủ nghĩa; cơ cấu xã hội - giai cấp và liên minh giai cấp, tầng lớp; vấn đề dân tộc và tôn giáo; vấn đề gia đình trong thời kỳ quá độ lên chủ nghĩa xã hội ở Việt Nam.
- Nếu câu hỏi NẰM NGOÀI phạm vi trên (ví dụ: dịch từ vựng, toán, lập trình, giải trí, đời sống chung...), hãy LỊCH SỰ TỪ CHỐI một cách ngắn gọn và hướng người dùng quay lại chủ đề chính. TUYỆT ĐỐI KHÔNG trả lời nội dung ngoài phạm vi rồi gượng ép gắn ghép vào chủ nghĩa Mác - Lênin để hợp thức hóa.
  Ví dụ từ chối: "Câu hỏi này nằm ngoài phạm vi của mình. Mình ở đây để đồng hành cùng bạn về chủ nghĩa Mác - Lênin và chủ nghĩa xã hội khoa học — bạn muốn tìm hiểu điều gì trong các chủ đề này không?"

**CĂN CỨ TRẢ LỜI & ĐỘ TIN CẬY (QUAN TRỌNG):**
- Phần "TRÍCH DẪN TỪ GIÁO TRÌNH" ở cuối (nếu có) là CĂN CỨ ƯU TIÊN SỐ MỘT. Hãy bám sát, trích dẫn và diễn giải đúng nội dung trong đó; KHÔNG thay thế nội dung giáo trình bằng kiến thức bên ngoài.
- Với các câu hỏi dạng LIÊN HỆ THỰC TIỄN, ĐÁNH GIÁ, CƠ HỘI VÀ THÁCH THỨC, VẬN DỤNG VÀO VIỆT NAM HIỆN NAY: hãy XUẤT PHÁT từ quan điểm, nguyên lý và luận điểm trong trích dẫn, rồi mới phân tích, liên hệ và mở rộng trên nền tảng đó. Luôn neo phần phân tích vào các luận điểm có trong giáo trình, dẫn lại ý của giáo trình trước khi mở rộng.
- Nếu trích dẫn chưa đủ chi tiết cho phần liên hệ/vận dụng, được phép mở rộng hợp lý nhưng phải NÓI RÕ đâu là nội dung từ giáo trình, đâu là phần liên hệ/suy luận thêm.
- Khi nêu trích dẫn, sự kiện, mốc thời gian: chỉ dùng dẫn chứng CHÍNH THỐNG, có thật (C. Mác, Ph. Ăngghen, V.I. Lênin, giáo trình và văn kiện chính thống). TUYỆT ĐỐI KHÔNG bịa câu nói, số liệu, sự kiện hay nguồn; không chắc thì nói thẳng là không chắc thay vì tự nghĩ ra.

**Hướng dẫn:**
- Luôn trả lời bằng tiếng Việt
- Giữ tone tích cực, khích lệ, không quá dài (2-3 đoạn)
- Không cần chào hỏi dài dòng hay tự giới thiệu lại ở mỗi câu trả lời; đi thẳng vào nội dung người dùng hỏi
- Nếu không chắc, nói thẳng thắn
- Hạn chế sử dụng các format phức tạp, giữ câu trả lời dễ đọc
- Hạn chế dùng chú thích trong ngoặc đơn lồng ngoặc kép; nếu cần nhấn mạnh một cụm từ thì chỉ dùng ngoặc kép, không bọc thêm ngoặc đơn bên ngoài${relevantContext}`
}

function sseEncode(event: string, data: unknown): Uint8Array {
  return new TextEncoder().encode(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`)
}

export async function POST(request: Request) {
  const apiKey = getApiKey()
  if (!apiKey) {
    return new Response(JSON.stringify({ error: 'Chưa cấu hình GOOGLE_API_KEY.' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  let body: { message?: string; history?: HistoryItem[] }
  try {
    body = await request.json()
  } catch {
    return new Response(JSON.stringify({ error: 'Body không hợp lệ.' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  const userMessage = (body.message ?? '').trim()
  if (!userMessage) {
    return new Response(JSON.stringify({ error: 'Thiếu nội dung câu hỏi.' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  const history = Array.isArray(body.history) ? body.history : []
  const relevantContext = await buildRelevantContext(userMessage)

  const contents = [
    { role: 'user', parts: [{ text: buildSystemPrompt(relevantContext) }] },
    ...history.map((msg) => ({
      role: msg.role === 'assistant' ? 'model' : 'user',
      parts: [{ text: msg.content ?? msg.text ?? '' }],
    })),
  ]

  const upstream = await fetch(`${CHAT_API_BASE}:streamGenerateContent?alt=sse&key=${apiKey}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ contents, generationConfig: GENERATION_CONFIG, safetySettings: SAFETY_SETTINGS }),
  })

  if (!upstream.ok || !upstream.body) {
    const detail = await upstream.text().catch(() => '')
    return new Response(JSON.stringify({ error: `Lỗi từ AI (${upstream.status}). ${detail.slice(0, 200)}` }), {
      status: 502,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  // Re-stream the upstream Gemini SSE as our own chunk/done/error events.
  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      const reader = upstream.body!.getReader()
      const decoder = new TextDecoder()
      let buffer = ''
      let emitted = false

      try {
        while (true) {
          const { done, value } = await reader.read()
          if (done) break

          buffer += decoder.decode(value, { stream: true })
          const lines = buffer.split('\n')
          buffer = lines.pop() ?? ''

          for (const line of lines) {
            const trimmed = line.trim()
            if (!trimmed.startsWith('data:')) continue
            const payload = trimmed.slice(5).trim()
            if (!payload || payload === '[DONE]') continue
            try {
              const data = JSON.parse(payload)
              const chunk = data?.candidates?.[0]?.content?.parts?.[0]?.text ?? ''
              if (chunk) {
                emitted = true
                controller.enqueue(sseEncode('chunk', { text: chunk }))
              }
            } catch {
              // ignore partial / keep-alive lines
            }
          }
        }

        if (!emitted) {
          controller.enqueue(sseEncode('error', { message: 'AI không trả về nội dung.' }))
        } else {
          controller.enqueue(sseEncode('done', {}))
        }
      } catch (error) {
        const message = error instanceof Error ? error.message : 'Streaming bị gián đoạn.'
        controller.enqueue(sseEncode('error', { message }))
      } finally {
        controller.close()
      }
    },
  })

  return new Response(stream, {
    headers: {
      'Content-Type': 'text/event-stream; charset=utf-8',
      'Cache-Control': 'no-cache, no-transform',
      Connection: 'keep-alive',
    },
  })
}
